export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLETED_TODO = "MARK_COMPLETED_TODO";
export const MARK_ALL_COMPLETED_TODO = "MARK_ALL_COMPLETED_TODO";
export const MARK_INCOMPLETED_TODO = "MARK_INCOMPLETED_TODO";
export const FILTER_TODO = "FILTER_TODO";
export const SEARCH_TODO = "SEARCH_TODO";